workflows:
  your-workflow-name:
    environment:
      groups:
        - FIREBASE_CREDENTIALS  # Import the FIREBASE_CREDENTIALS group
        - MERCADO_PAGO              # Import the MERCADO PAGO group
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
      - name: Decode Google Play Service Account JSON
        script: |
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > google-play-service-account.json

publishing:
  google_play:
    service_account_json_path: google-play-service-account.json # Use the file you just created
    #... rest of your Google Play publishing config

    # ... rest of your Codemagic configuration (build commands, etc.)