workflows:
  your-workflow-name:
    environment:
      groups:
        - FIREBASE_CREDENTIALS  # Import the FIREBASE_CREDENTIALS group
        - MERCADO_PAGO              # Import the MERCADO PAGO group
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
    # ... rest of your Codemagic configuration (build commands, etc.)