workflows:
  android-build:  # Workflow for Android
    name: Android Build
    instance_type: mac_mini_m2  # Use mac_mini_m2 for macOS M2
    environment:
      flutter: 3.22.2 # stable # or '3.7.6', 'beta', 'master', etc.
      groups:
        - FIREBASE_CREDENTIALS  # Import the FIREBASE_CREDENTIALS group
        - MERCADO_PAGO              # Import the MERCADO PAGO group
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches  # Include the Gradle user cache as well. This is good practice.
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
      - name: Decode Google Play Service Account JSON
        script: |
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > google-play-service-account.json
      - name: Install JDK 17
        script: |
          # Install Temurin JDK 17 using Homebrew
          brew install temurin17

          # Set JAVA_HOME
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)

          # Verify installation
          java -version
      - name: Verify Flutter 3.22.2
        script: |
          # Verify installation
          flutter doctor -v
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android App
        script: |
          flutter build appbundle --release --verbose --dart-define=FIREBASE_API_KEY="$FIREBASE_API_KEY" --dart-define=FIREBASE_APP_ID="$FIREBASE_APP_ID" --dart-define=KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" --dart-define=KEY_ALIAS="$KEY_ALIAS" --dart-define=KEY_PASSWORD="$KEY_PASSWORD" --dart-define=KEYSTORE_BASE64="$KEYSTORE_BASE64" --dart-define=MP_ACCESS_TOKEN_SELLER="$MP_ACCESS_TOKEN_SELLER"
      - name: Print missing rules
        script: |
          cat /Users/builder/clone/build/app/outputs/mapping/release/missing_rules.txt

publishing:
  google_play:
    service_account_json_path: google-play-service-account.json # Use the file you just created
    #... rest of your Google Play publishing config

    # ... rest of your Codemagic configuration (build commands, etc.)