workflows:
  your-workflow-name:
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home # 1.8.0_412 - Or the appropriate path for the JDK you install
      groups:
        - FIREBASE_CREDENTIALS  # Import the FIREBASE_CREDENTIALS group
        - MERCADO_PAGO              # Import the MERCADO PAGO group
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
      - name: Decode Google Play Service Account JSON
        script: |
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > google-play-service-account.json
      - name: Install JDK 18
        script: |
          sudo apt-get update  # Update package lists (if needed)
          sudo apt-get install -y zulu-8 # Install Zulu JDK 18 (or the JDK of your choice)

          # Verify the installation and set JAVA_HOME
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home # Or the correct path if different
          java -version # Check if the correct JDK is installed
      - name: Build Android App
        script: |
          flutter build appbundle --release --verbose --dart-define=FIREBASE_API_KEY="$FIREBASE_API_KEY" --dart-define=FIREBASE_APP_ID="$FIREBASE_APP_ID" --dart-define=KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" --dart-define=KEY_ALIAS="$KEY_ALIAS" --dart-define=KEY_PASSWORD="$KEY_PASSWORD" --dart-define=KEYSTORE_BASE64="$KEYSTORE_BASE64" --dart-define=MP_ACCESS_TOKEN_SELLER="$MP_ACCESS_TOKEN_SELLER"

publishing:
  google_play:
    service_account_json_path: google-play-service-account.json # Use the file you just created
    #... rest of your Google Play publishing config

    # ... rest of your Codemagic configuration (build commands, etc.)