workflows:
  android-build:  # Workflow for Android
    name: Android Build
    instance_type: mac_mini_m2  # Use mac_mini_m2 for macOS M2
    environment:
      android_signing:
        - mobxmvvm
      vars:
        PACKAGE_NAME: "br.com.ccortez.mobx_mvvm" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "alpha"
      flutter: 3.22.2 # stable # or '3.7.6', 'beta', 'master', etc.
      groups:
        - FIREBASE_CREDENTIALS  # Import the FIREBASE_CREDENTIALS group
        - MERCADO_PAGO              # Import the MERCADO PAGO group
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches  # Include the Gradle user cache as well. This is good practice.
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
      - name: Decode Google Play Service Account JSON
        script: |
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > google-play-service-account.json
      - name: Install JDK 17
        script: |
          # Install Temurin JDK 17 using Homebrew
          brew install temurin17

          # Set JAVA_HOME
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)

          # Verify installation
          java -version
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Verify Flutter 3.22.2
        script: |
          # Verify installation
          flutter doctor -v
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android App (AAB with Flutter)
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release --verbose --no-shrink --dart-define=FIREBASE_API_KEY="$FIREBASE_API_KEY" --dart-define=FIREBASE_APP_ID="$FIREBASE_APP_ID" --dart-define=KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" --dart-define=KEY_ALIAS="$KEY_ALIAS" --dart-define=KEY_PASSWORD="$KEY_PASSWORD" --dart-define=KEYSTORE_BASE64="$KEYSTORE_BASE64" --dart-define=MP_ACCESS_TOKEN_SELLER="$MP_ACCESS_TOKEN_SELLER" \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
#      - /Users/builder/clone/build/**
    publishing:
      email:
        recipients:
          - cristianocortez@gmail.com
#          - user_2@example.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
#        service_account_json_path: google-play-service-account.json # Use the file you just created
