// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mvvm_mobx_github/integration_test/helpers/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_mvvm_mobx_github/features/domain/entities/post.dart'
    as _i4;
import 'package:flutter_mvvm_mobx_github/features/domain/entities/produto.dart'
    as _i6;
import 'package:flutter_mvvm_mobx_github/features/domain/repositories/i_post_repository.dart'
    as _i2;
import 'package:flutter_mvvm_mobx_github/features/domain/repositories/i_preference_repository.dart'
    as _i7;
import 'package:flutter_mvvm_mobx_github/features/domain/repositories/i_produto_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPostRepository extends _i1.Mock implements _i2.IPostRepository {
  MockIPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Post>> getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
          )
          as _i3.Future<List<_i4.Post>>);
}

/// A class which mocks [IProdutoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProdutoRepository extends _i1.Mock
    implements _i5.IProdutoRepository {
  MockIProdutoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Produto>> getProdutos() =>
      (super.noSuchMethod(
            Invocation.method(#getProdutos, []),
            returnValue: _i3.Future<List<_i6.Produto>>.value(<_i6.Produto>[]),
          )
          as _i3.Future<List<_i6.Produto>>);
}

/// A class which mocks [IPreferenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPreferenceRepository extends _i1.Mock
    implements _i7.IPreferenceRepository {
  MockIPreferenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createPreference(List<_i6.Produto>? cartItems) =>
      (super.noSuchMethod(
            Invocation.method(#createPreference, [cartItems]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createPreference, [cartItems]),
              ),
            ),
          )
          as _i3.Future<String>);
}
